QNLP: /Users/mlxd/Desktop/intel-qnlp-rc2/modules/io/db/test_db.cpp File Reference
test_db.cpp File Reference
Unit tests for the 'db' module. Classes tested: [DBHelper, CorpusUtils].
#include <fstream>
#include <cstdlib>
#include "db_helper.hpp"
#include "corpus_utils.hpp"
#include "catch2/catch.hpp"
Functions
TEST_CASE ("DBHelper unit tests: Default constructor: DBHelper()","[db]")
Testing default constructor and subsequent functions on DBHelper class.
TEST_CASE ("Parameterised constructor: DBHelper(const std::string filename) with 'test.db'","[db]")
Testing parameterised constructor and subsequent functions on DBHelper class with given database 'test.db'.
TEST_CASE ("Parameterised constructor: DBHelper(const std::string filename) with 'none.db'","[db]")
Testing parameterised constructor and subsequent functions on DBHelper class with non-existant database 'none.db'.
TEST_CASE ("CorpusUtils unit tests: Default constructor: CorpusUtils()","[db]")
Testing default constructor and subsequent functions on CorpusUtils class.
TEST_CASE ("CorpusUtils unit tests: Paramaterised constructor: CorpusUtils(test_db.db)","[db]")
Testing parameterised constructor and subsequent functions on CorpusUtils class.
Detailed Description
Unit tests for the 'db' module. Classes tested: [DBHelper, CorpusUtils].
Author
Lee J. O'Riordan (lee.o.nosp@m.rior.nosp@m.dan@i.nosp@m.chec.nosp@m..ie)
Version
0.1
Date
2019-05-01
Copyright
Copyright (c) 2019
Definition in file test_db.cpp.
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("DBHelper unit tests: Default constructor: DBHelper()" , "" [db])
Testing default constructor and subsequent functions on DBHelper class.
Definition at line 28 of file test_db.cpp.
                               : Default constructor: DBHelper()","[db]"){
     DBHelper db;
     //REQUIRE(db.getFilename() == "qnlp_tagged_corpus.sqlite");
     REQUIRE(db.getFilename() == "");
     REQUIRE(db.getDBRef() == nullptr);
     SECTION("openDB(const std::string filename) with 'test_db.db'"){
         int ret_code = db.openDB("test_db.db");
         REQUIRE(ret_code == 0);
         REQUIRE(db.getDBRef() != nullptr);
         REQUIRE(db.getFilename().compare("test_db.db") == 0);
         SECTION("closeDB()"){
             db.closeDB();
             REQUIRE(db.getFilename() == "");
             REQUIRE(db.getDBRef() == nullptr );
         }
     }
     SECTION("openDB(const std::string filename) with 'none.db'"){
         REQUIRE(db.openDB("none.db") != 0);
         REQUIRE(db.getDBRef() == nullptr);
         REQUIRE(db.getFilename().compare("") == 0);
         SECTION("closeDB()"){
             db.closeDB();
             REQUIRE(db.getFilename() == "");
             REQUIRE(db.getDBRef() == nullptr );
         }
     }
 }
References QNLP::DBHelper::closeDB(), QNLP::DBHelper::getDBRef(), QNLP::DBHelper::getFilename(), and QNLP::DBHelper::openDB().
TEST_CASE() [2/5]
TEST_CASE ("Parameterised constructor: DBHelper(const std::string filename) with 'test.db'" , "" [db])
Testing parameterised constructor and subsequent functions on DBHelper class with given database 'test.db'.
Definition at line 65 of file test_db.cpp.
                                     : DBHelper(const std::string filename) with 'test.db'","[db]"){
     DBHelper db("test_db.db");
     REQUIRE(db.getFilename() == "test_db.db");
     REQUIRE(db.getDBRef() != nullptr);
     SECTION("openDB(const std::string filename) with 'test_db.db'"){
         REQUIRE(db.openDB("test_db.db") == 0);
         REQUIRE(db.getDBRef() != nullptr);
         REQUIRE(db.getFilename().compare("test_db.db") == 0);
     }
     SECTION("closeDB()"){
         db.closeDB();
         REQUIRE(db.getFilename() == "");
         REQUIRE(db.getDBRef() == nullptr );
     }
 }
References QNLP::DBHelper::closeDB(), QNLP::DBHelper::getDBRef(), QNLP::DBHelper::getFilename(), and QNLP::DBHelper::openDB().
TEST_CASE() [3/5]
TEST_CASE ("Parameterised constructor: DBHelper(const std::string filename) with 'none.db'" , "" [db])
Testing parameterised constructor and subsequent functions on DBHelper class with non-existant database 'none.db'.
Definition at line 88 of file test_db.cpp.
                                     : DBHelper(const std::string filename) with 'none.db'","[db]"){
     DBHelper db("none.db");
     REQUIRE(db.getFilename() == "");
     REQUIRE(db.getDBRef() == nullptr);
     SECTION("openDB(const std::string filename) with 'none.db'"){
         REQUIRE(db.openDB("none.db") != 0 );
         REQUIRE(db.getDBRef() == nullptr);
         REQUIRE(db.getFilename().compare("") == 0);
     }
     SECTION("closeDB()"){
         db.closeDB();
         REQUIRE(db.getFilename() == "");
         REQUIRE(db.getDBRef() == nullptr );
     }
 }
References QNLP::DBHelper::closeDB(), QNLP::DBHelper::getDBRef(), QNLP::DBHelper::getFilename(), and QNLP::DBHelper::openDB().
TEST_CASE() [4/5]
TEST_CASE ("CorpusUtils unit tests: Default constructor: CorpusUtils()" , "" [db])
Testing default constructor and subsequent functions on CorpusUtils class.
Definition at line 110 of file test_db.cpp.
                                  : Default constructor: CorpusUtils()","[db]"){
     CorpusUtils cu;
     REQUIRE(cu.getBinToName().size() == 0);
     REQUIRE(cu.getNameToBin().size() == 0);
     REQUIRE(cu.get_database_filename().compare("qnlp_tagged_corpus.sqlite") == 0);
     REQUIRE(cu.getDBHelper().getFilename().compare("qnlp_tagged_corpus.sqlite") == 0);
     REQUIRE(cu.getDBHelper().getDBRef() != nullptr);
     SECTION("Load data: data_type=noun, table is default ('corpus')"){
         cu.loadData("noun");
         std::size_t n_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(n_size[0] != 0);
         REQUIRE(n_size[1] != 0);
     }
     SECTION("Load data: data_type=verb, table is default ('corpus')"){
         cu.loadData("verb");
         std::size_t v_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(v_size[0] != 0);
         REQUIRE(v_size[1] != 0);
     }
     SECTION("Load data: data_type=noun and verb, table is default ('corpus')"){
         cu.loadData("verb");
         std::size_t v_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(v_size[0] != 0);
         REQUIRE(v_size[1] != 0);
         cu.loadData("noun");
         std::size_t vn_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(vn_size[0] != v_size[0]);
         REQUIRE(vn_size[1] != v_size[1]);
     }
     SECTION("Load data: data_type=noun and verb, table='basis'"){
         cu.loadData("verb", "basis");
         std::size_t v_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(v_size[0] != 0);
         REQUIRE(v_size[1] != 0);
         cu.loadData("noun", "basis");
         std::size_t vn_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(vn_size[0] != v_size[0]);
         REQUIRE(vn_size[1] != v_size[1]);
     }
 }
References QNLP::CorpusUtils::get_database_filename(), QNLP::CorpusUtils::getBinToName(), QNLP::CorpusUtils::getDBHelper(), QNLP::DBHelper::getDBRef(), QNLP::DBHelper::getFilename(), QNLP::CorpusUtils::getNameToBin(), and QNLP::CorpusUtils::loadData().
TEST_CASE() [5/5]
TEST_CASE ("CorpusUtils unit tests: Paramaterised constructor: CorpusUtils(test_db.db)" , "" [db])
Testing parameterised constructor and subsequent functions on CorpusUtils class.
Definition at line 159 of file test_db.cpp.
                                  : Paramaterised constructor: CorpusUtils(test_db.db)","[db]"){
     CorpusUtils cu("test_db.db");
     REQUIRE(cu.getBinToName().size() == 0);
     REQUIRE(cu.getNameToBin().size() == 0);
     REQUIRE(cu.get_database_filename() == cu.getDBHelper().getFilename());
     REQUIRE(cu.get_database_filename().compare("test_db.db") == 0);
     REQUIRE(cu.getDBHelper().getFilename().compare("test_db.db") == 0);
     REQUIRE(cu.getDBHelper().getDBRef() != nullptr);
     SECTION("Load data: data_type=noun, table is default ('corpus')"){
         cu.loadData("noun");
         std::size_t n_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(n_size[0] != 0);
         REQUIRE(n_size[1] != 0);
     }
     SECTION("Load data: data_type=verb, table is default ('corpus')"){
         cu.loadData("verb");
         std::size_t v_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(v_size[0] != 0);
         REQUIRE(v_size[1] != 0);
     }
     SECTION("Load data: data_type=noun and verb, table is default ('corpus')"){
         cu.loadData("verb");
         std::size_t v_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(v_size[0] != 0);
         REQUIRE(v_size[1] != 0);
         cu.loadData("noun");
         std::size_t vn_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(vn_size[0] != v_size[0]);
         REQUIRE(vn_size[1] != v_size[1]);
     }
     SECTION("Load data: data_type=noun and verb, table='basis'"){
         cu.loadData("verb", "basis");
         std::size_t v_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(v_size[0] != 0);
         REQUIRE(v_size[1] != 0);
         cu.loadData("noun", "basis");
         std::size_t vn_size[2] = {cu.getBinToName().size(), cu.getNameToBin().size()};
         REQUIRE(vn_size[0] != v_size[0]);
         REQUIRE(vn_size[1] != v_size[1]);
     }
 }
References QNLP::CorpusUtils::get_database_filename(), QNLP::CorpusUtils::getBinToName(), QNLP::CorpusUtils::getDBHelper(), QNLP::DBHelper::getDBRef(), QNLP::DBHelper::getFilename(), QNLP::CorpusUtils::getNameToBin(), and QNLP::CorpusUtils::loadData().