QNLP: QNLP::BitGroup< SimulatorType > Class Template Reference
QNLP::BitGroup< SimulatorType > Class Template Reference
Class definition for bit-wise grouping in register.
#include <bit_group.hpp>
Static Public Member Functions
static void bit_group (SimulatorType &qSim, const std::vector< std::size_t > &qreg_idx, const std::vector< std::size_t > &qaux_idx, bool lsb=true)
Swaps all qubits in register indices given by qreg_idx to their right-most positions. Method works by pairing qubits using even-odd indexed cycles iteratively until all qubits are in the correct positions. Intermediate qubit reset operation may not be realisable on all platforms (Hadarmard followed by SigmaZ projection to |0>)
Static Private Member Functions
static void q_ops (SimulatorType &qSim, std::size_t qreg_idx0, std::size_t qreg_idx1, const std::vector< std::size_t > &qaux_idx)
Swap the qubits if qreg_idx0 is set and qreg_idx1 is not. Uses Auxiliary qubits qaux_idx which are set to |10> at start and end of operations.
static void bit_swap_pair (SimulatorType &qSim, const std::vector< std::size_t > &qreg_idx, const std::vector< std::size_t > &qaux_idx, bool lsb)
Swaps all qubits in register indices given by qreg_idx to their right-most positions. Method works by pairing qubits using even-odd indexed cycles iteratively until all qubits are in the correct positions.
Detailed Description
template<class SimulatorType>
class QNLP::BitGroup< SimulatorType >
Class definition for bit-wise grouping in register.
Template Parameters
SimulatorType
Definition at line 25 of file bit_group.hpp.
Member Function Documentation
bit_group()
template<class SimulatorType > static void QNLP::BitGroup< SimulatorType >::bit_group (SimulatorType & qSim, const std::vector< std::size_t > & qreg_idx, const std::vector< std::size_t > & qaux_idx, bool lsb = true) inline static
Swaps all qubits in register indices given by qreg_idx to their right-most positions. Method works by pairing qubits using even-odd indexed cycles iteratively until all qubits are in the correct positions. Intermediate qubit reset operation may not be realisable on all platforms (Hadarmard followed by SigmaZ projection to |0>)
Parameters
qSim Quantum simulator object derived from SimulatorGeneral
qreg_idx Indices of the qSim register to group to the LSB position.
qaux_idx Indices of auxiliary qubits in qSim register in |00> state
lsb Indicates if to shift the values to the MSB or LSB equivalent positions.
Definition at line 114 of file bit_group.hpp.
{
             bit_swap_pair(qSim, qreg_idx, qaux_idx, lsb);
         }
References QNLP::BitGroup< SimulatorType >::bit_swap_pair().
Referenced by QNLP::SimulatorGeneral< IntelSimulator >::groupQubits(), and TEST_CASE().
bit_swap_pair()
template<class SimulatorType > static void QNLP::BitGroup< SimulatorType >::bit_swap_pair (SimulatorType & qSim, const std::vector< std::size_t > & qreg_idx, const std::vector< std::size_t > & qaux_idx, bool lsb) inline static private
Swaps all qubits in register indices given by qreg_idx to their right-most positions. Method works by pairing qubits using even-odd indexed cycles iteratively until all qubits are in the correct positions.
Parameters
qSim Quantum simulator object derived from SimulatorGeneral
qreg_idx Indices of the qSim register to group to the LSB position.
qaux_idx Indices of auxiliary qubits in qSim register in |00> state
Definition at line 83 of file bit_group.hpp.
{
             bool isOdd = qreg_idx.size() % 2;
             qSim.applyGateX(qaux_idx[0]);
             for(std::size_t num_steps = 0; num_steps < qreg_idx.size(); num_steps++){
                 for(int i = 0; i < qreg_idx.size()-1; i+=2){
                     if(i + 1 + isOdd < qreg_idx.size()){
                         if(lsb)
                             q_ops(qSim,  qreg_idx[i + isOdd], qreg_idx[i + 1 + isOdd], qaux_idx);
                         else
                             q_ops(qSim,  qreg_idx[i + 1 + isOdd], qreg_idx[i + isOdd], qaux_idx);
                     }
                 }
                 isOdd = !isOdd;
             }
             qSim.applyGateX(qaux_idx[0]);
         }
References QNLP::BitGroup< SimulatorType >::q_ops().
Referenced by QNLP::BitGroup< SimulatorType >::bit_group().
q_ops()
template<class SimulatorType > static void QNLP::BitGroup< SimulatorType >::q_ops (SimulatorType & qSim, std::size_t qreg_idx0, std::size_t qreg_idx1, const std::vector< std::size_t > & qaux_idx) inline static private
Swap the qubits if qreg_idx0 is set and qreg_idx1 is not. Uses Auxiliary qubits qaux_idx which are set to |10> at start and end of operations.
Parameters
qSim Quantum simulator object derived from SimulatorGeneral
qreg_idx0 Index of qubit 0 in qSim qubit register
qreg_idx1 Index of qubit 1 in qSim qubit register
qaux_idx Indices of auxiliary qubits in qSim qubit register that are set to |10>
Definition at line 36 of file bit_group.hpp.
{
             //Swap if C0 is set and C1 is not
             qSim.applyGateCCX(qreg_idx0, qaux_idx[0], qaux_idx[1]);
             qSim.applyGateCCX(qreg_idx1, qreg_idx0, qaux_idx[1]);
             qSim.applyGateCSwap(qaux_idx[1], qreg_idx0, qreg_idx1);
             //Reset Aux gate to |0>
             qSim.applyGateH(qaux_idx[1]);
             qSim.collapseToBasisZ(qaux_idx[1], 0);
         }
Referenced by QNLP::BitGroup< SimulatorType >::bit_swap_pair().
The documentation for this class was generated from the following file:
/Users/mlxd/Desktop/intel-qnlp-rc2/modules/gate_ops/bit_group/bit_group.hpp