QNLP: QNLP::CorpusUtils Class Reference
QNLP::CorpusUtils Class Reference
#include <corpus_utils.hpp>
Public Types
typedef std::unordered_map< std::string, std::unordered_map< std::string, unsigned int > > NTB
typedef std::unordered_map< std::string, std::unordered_map< unsigned int, std::string > > BTN
Public Member Functions
CorpusUtils ()
Construct a new Load Corpus object. Database name taken from the macro/compiler defined value.
CorpusUtils (const std::string filename)
Construct a new Load Corpus object. Database name given explicitly.
~CorpusUtils ()
NTB & getNameToBin ()
Get the NTB object. This is a map of maps, wherein the first key represents the grammatical type to load. The second key accesses the name to binary string mapping data, wherein each unique entity has a mapping to a unique binary string, which will representation it's encoding in the quantum state-space.
BTN & getBinToName ()
Get the BTN object. This is a map of maps, wherein the first key represents the grammatical type to load. The second key accesses binary mapping data, wherein each unique entity has a mapping to a unique string entity. This allows for determining a result upon measurement of the quantum state-space back to a specific meaning eneity.
void loadData (const std::string data_type, const std::string table="corpus")
Loads from the database for a given data type (noun, verb, etc)
DBHelper & getDBHelper ()
Return reference to database object.
void printData (const std::string type, const std::string table)
Print the data with given type.
const std::string get_database_filename ()
Get the database filename object.
void clearData ()
Clear all loaded data.
Private Attributes
NTB name_to_bin
BTN bin_to_name
DBHelper db_helper
std::string database_filename
Detailed Description
Definition at line 19 of file corpus_utils.hpp.
Member Typedef Documentation
BTN
typedef std::unordered_map<std::string, std::unordered_map<unsigned int, std::string> > QNLP::CorpusUtils::BTN
Definition at line 36 of file corpus_utils.hpp.
NTB
typedef std::unordered_map<std::string, std::unordered_map<std::string, unsigned int> > QNLP::CorpusUtils::NTB
Definition at line 35 of file corpus_utils.hpp.
Constructor & Destructor Documentation
CorpusUtils() [1/2]
CorpusUtils::CorpusUtils ()
Construct a new Load Corpus object. Database name taken from the macro/compiler defined value.
Definition at line 15 of file corpus_utils.cpp.
                          :
     db_helper(QNLP_DB_FILE), database_filename(QNLP_DB_FILE) {}
CorpusUtils() [2/2]
CorpusUtils::CorpusUtils (const std::string filename)
Construct a new Load Corpus object. Database name given explicitly.
Parameters
filename Database filename
Definition at line 19 of file corpus_utils.cpp.
                                                  :
     db_helper(filename), database_filename(filename) {}
~CorpusUtils()
CorpusUtils::~CorpusUtils ()
Definition at line 22 of file corpus_utils.cpp.
{
     CorpusUtils::clearData();
 }
References clearData().
Member Function Documentation
clearData()
void CorpusUtils::clearData ()
Clear all loaded data.
Definition at line 70 of file corpus_utils.cpp.
{
     this->bin_to_name.clear();
     this->name_to_bin.clear();
 }
References bin_to_name, and name_to_bin.
Referenced by ~CorpusUtils().
get_database_filename()
const std::string CorpusUtils::get_database_filename ()
Get the database filename object.
Returns
const std::string
Definition at line 66 of file corpus_utils.cpp.
{
     return this->database_filename;
 }
References database_filename.
Referenced by TEST_CASE().
getBinToName()
CorpusUtils::BTN & CorpusUtils::getBinToName ()
Get the BTN object. This is a map of maps, wherein the first key represents the grammatical type to load. The second key accesses binary mapping data, wherein each unique entity has a mapping to a unique string entity. This allows for determining a result upon measurement of the quantum state-space back to a specific meaning eneity.
Returns
BTN&
Definition at line 30 of file corpus_utils.cpp.
{
     return this->bin_to_name;
 }
References bin_to_name.
Referenced by TEST_CASE().
getDBHelper()
DBHelper & CorpusUtils::getDBHelper ()
Return reference to database object.
Returns
DB& reference to database object
Definition at line 75 of file corpus_utils.cpp.
{
     return this->db_helper;
 }
References db_helper.
Referenced by loadData(), and TEST_CASE().
getNameToBin()
CorpusUtils::NTB & CorpusUtils::getNameToBin ()
Get the NTB object. This is a map of maps, wherein the first key represents the grammatical type to load. The second key accesses the name to binary string mapping data, wherein each unique entity has a mapping to a unique binary string, which will representation it's encoding in the quantum state-space.
Returns
NTB&
Definition at line 26 of file corpus_utils.cpp.
{
     return this->name_to_bin;
 }
References name_to_bin.
Referenced by TEST_CASE().
loadData()
void CorpusUtils::loadData (const std::string data_type, const std::string table = "corpus")
Loads from the database for a given data type (noun, verb, etc)
Parameters
data_type String of the data type to load
table Database table to load data from
Definition at line 34 of file corpus_utils.cpp.
{
     int rc;
     sqlite3_stmt *select_stmt = NULL;
     db_helper.openDB(database_filename);
     std::string query = "select name, bin_id from " + table + " where type=?";
     SQL_RETURN_CHECK ( sqlite3_prepare_v2( getDBHelper().getDBRef(), query.c_str(), -1, &select_stmt, NULL ), SQLITE_OK );
     //Arg 2 is the 1-based index of the variable to replace
     //Arg 4 is used to give the number of bytes, where -1 takes the length of string
     //Arg 5 specifies the destructor type, where SQLITE_STATIC causes it to ignore.
     SQL_RETURN_CHECK( sqlite3_bind_text( select_stmt, 1, data_type.c_str(), -1, SQLITE_STATIC ), SQLITE_OK );
     //Iterate through the rows of returned values
     while ( (rc = sqlite3_step(select_stmt)) == SQLITE_ROW) {
         std::string k( reinterpret_cast<const char*> ( sqlite3_column_text(select_stmt, 0) ) );
         unsigned int v = (unsigned int) sqlite3_column_int(select_stmt, 1);
         name_to_bin[data_type][k] = v;
         bin_to_name[data_type][v] = k;
     }
     SQL_RETURN_CHECK( sqlite3_finalize(select_stmt), SQLITE_OK );
 }
References bin_to_name, database_filename, db_helper, getDBHelper(), name_to_bin, QNLP::DBHelper::openDB(), and SQL_RETURN_CHECK.
Referenced by printData(), and TEST_CASE().
printData()
void CorpusUtils::printData (const std::string type, const std::string table = "corpus")
Print the data with given type.
Parameters
type Grammatical type
table Database table to print data from
Definition at line 57 of file corpus_utils.cpp.
{
     if(! this->name_to_bin.size()){
         loadData(type, table);
     }
     for(auto& dat : this->name_to_bin[type]){
         std::cout << dat.first << " : " << dat.second << std::endl;
     }
 }
References loadData(), and name_to_bin.
Field Documentation
bin_to_name
BTN QNLP::CorpusUtils::bin_to_name private
Definition at line 90 of file corpus_utils.hpp.
Referenced by clearData(), getBinToName(), and loadData().
database_filename
std::string QNLP::CorpusUtils::database_filename private
Definition at line 94 of file corpus_utils.hpp.
Referenced by get_database_filename(), and loadData().
db_helper
DBHelper QNLP::CorpusUtils::db_helper private
Definition at line 93 of file corpus_utils.hpp.
Referenced by getDBHelper(), and loadData().
name_to_bin
NTB QNLP::CorpusUtils::name_to_bin private
Definition at line 89 of file corpus_utils.hpp.
Referenced by clearData(), getNameToBin(), loadData(), and printData().
The documentation for this class was generated from the following files:
/Users/mlxd/Desktop/intel-qnlp-rc2/modules/io/db/corpus_utils.hpp
/Users/mlxd/Desktop/intel-qnlp-rc2/modules/io/db/corpus_utils.cpp