QNLP: QNLP.proc.HammingDistance.HammingDistanceOverwriteAux Class Reference
QNLP.proc.HammingDistance.HammingDistanceOverwriteAux Class Reference
Public Member Functions
def __init__ (self, num_bits, simulator)
def calc (self, reg_mem, reg_aux, pattern)
def calc (self)
Data Fields
num_bits
sim
Private Member Functions
def _encodePattern (self, reg_mem, reg_aux, pattern)
def _overwriteAux (self, reg_mem, reg_aux, pattern)
Detailed Description
Intermediate routine to overwrite the data in the aux register
with its Hamming dsiatnce to the data in the memory regsiter.
Definition at line 88 of file HammingDistance.py.
Constructor & Destructor Documentation
__init__()
def QNLP.proc.HammingDistance.HammingDistanceOverwriteAux.__init__ (self, num_bits, simulator)
Reimplemented from QNLP.proc.HammingDistance.HammingDistance.
Reimplemented in QNLP.proc.HammingDistance.HammingDistanceGroupRotate.
Definition at line 93 of file HammingDistance.py.
     def __init__(self, num_bits, simulator):
         super().__init__(num_bits,simulator)
Member Function Documentation
_encodePattern()
def QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._encodePattern (self, reg_mem, reg_aux, pattern) private
Definition at line 96 of file HammingDistance.py.
     def _encodePattern(self, reg_mem, reg_aux, pattern):
         self.sim.encodeToRegister(pattern, reg_aux[0:-2], len(reg_mem))
References QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceOverwriteAux.calc(), and QNLP.proc.HammingDistance.HammingDistanceGroupRotate.calc().
_overwriteAux()
def QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._overwriteAux (self, reg_mem, reg_aux, pattern) private
Definition at line 99 of file HammingDistance.py.
     def _overwriteAux(self, reg_mem, reg_aux, pattern):
         for idx, val in enumerate(reg_mem):
             self.sim.applyGateX(reg_aux[idx])
             self.sim.applyGateCCX(reg_mem[idx], reg_aux[idx], reg_aux[-2])
             self.sim.applyGateX(reg_aux[idx])
             self.sim.applyGateCSwap(reg_mem[idx], reg_aux[idx], reg_aux[-2])
References QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceOverwriteAux.calc(), and QNLP.proc.HammingDistance.HammingDistanceGroupRotate.calc().
calc() [1/2]
def QNLP.proc.HammingDistance.HammingDistance.calc (self) inherited
Definition at line 30 of file HammingDistance.py.
     def calc(self):
         pass
calc() [2/2]
def QNLP.proc.HammingDistance.HammingDistanceOverwriteAux.calc (self, reg_mem, reg_aux, pattern)
Reimplemented in QNLP.proc.HammingDistance.HammingDistanceGroupRotate.
Definition at line 106 of file HammingDistance.py.
     def calc(self, reg_mem, reg_aux, pattern):
         self._encodePattern(reg_mem, reg_aux, pattern)
         self._overwriteAux(reg_mem, reg_aux, pattern)
References QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._encodePattern(), and QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._overwriteAux().
Field Documentation
num_bits
QNLP.proc.HammingDistance.HammingDistance.num_bits inherited
Definition at line 18 of file HammingDistance.py.
Referenced by QNLP.proc.HammingDistance.HammingDistanceGroupRotate._oracle_angle_map().
sim
QNLP.proc.HammingDistance.HammingDistance.sim inherited
Definition at line 19 of file HammingDistance.py.
Referenced by QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._encodePattern(), QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._overwriteAux(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step1(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step2(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step3(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step4(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step5(), QNLP.proc.HammingDistance.HammingDistanceGroupRotate.calc(), QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming(), and QNLP.proc.HammingDistance.HammingDistanceExpITheta.hamming_aux_overwrite().
The documentation for this class was generated from the following file:
/Users/mlxd/Desktop/tmp/intel-qnlp-api/modules/py/pkgs/QNLP/proc/HammingDistance.py