QNLP: QNLP.proc.HammingDistance.HammingDistanceExpITheta Class Reference
QNLP.proc.HammingDistance.HammingDistanceExpITheta Class Reference
Public Member Functions
def __init__ (self, num_bits, simulator)
def encode_hamming (self, reg_mem, reg_aux, pattern)
def hamming_aux_overwrite (self, reg_mem, reg_aux)
def calc (self, reg_mem, reg_aux, pattern)
def calc (self)
Data Fields
num_bits
sim
Private Member Functions
def _step1 (self, reg_mem, reg_aux, pattern)
def _step2 (self, reg_mem, reg_aux)
def _step3 (self, reg_mem, reg_aux)
def _step4 (self, reg_mem, reg_aux)
def _step5 (self, reg_aux)
Detailed Description
Default approach taken by Trugenberger, and others to encode
Hamming distance into the state phase. Results can be skewed
by high degeneracy in encoded patterns.
Definition at line 33 of file HammingDistance.py.
Constructor & Destructor Documentation
__init__()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta.__init__ (self, num_bits, simulator)
Reimplemented from QNLP.proc.HammingDistance.HammingDistance.
Definition at line 39 of file HammingDistance.py.
     def __init__(self, num_bits, simulator):
         super().__init__(num_bits, simulator)
Member Function Documentation
_step1()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta._step1 (self, reg_mem, reg_aux, pattern) private
Definition at line 42 of file HammingDistance.py.
     def _step1(self, reg_mem, reg_aux, pattern):
         self.sim.encodeToRegister(pattern, reg_aux[0:-2], len(reg_mem))
References QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming().
_step2()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta._step2 (self, reg_mem, reg_aux) private
Definition at line 45 of file HammingDistance.py.
     def _step2(self, reg_mem, reg_aux):
         for i in range(len(reg_aux)-2):
             self.sim.applyGateCX(reg_aux[i], reg_mem[i])
             self.sim.applyGateX(reg_mem[i])
References QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming().
_step3()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta._step3 (self, reg_mem, reg_aux) private
Definition at line 50 of file HammingDistance.py.
     def _step3(self, reg_mem, reg_aux):
         theta = np.pi / (2.0 * len(reg_mem))
         UMat = self._UMatrix(theta)
         CUMatPowMin2 = self._UMatrixPowMin2(theta)
         for j in range(len(reg_mem)):
             self.sim.applyGateU(UMat, reg_mem[j], "U")
         for i in range(len(reg_mem)):
             self.sim.applyGateCU(CUMatPowMin2, reg_aux[-2], reg_mem[i], "U")
References QNLP.proc.HammingDistance.HammingDistance._UMatrix(), QNLP.proc.HammingDistance.HammingDistance._UMatrixPowMin2(), and QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming().
_step4()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta._step4 (self, reg_mem, reg_aux) private
Definition at line 61 of file HammingDistance.py.
     def _step4(self, reg_mem, reg_aux):
         for i in range(len(reg_aux)-2):
             self.sim.applyGateX(reg_mem[i])
             self.sim.applyGateCX(reg_aux[i], reg_mem[i])
References QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming().
_step5()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta._step5 (self, reg_aux) private
Definition at line 66 of file HammingDistance.py.
     def _step5(self, reg_aux):
         self.sim.collapseToBasisZ(reg_aux[-2], False)
References QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming().
calc() [1/2]
def QNLP.proc.HammingDistance.HammingDistance.calc (self) inherited
Definition at line 30 of file HammingDistance.py.
     def calc(self):
         pass
calc() [2/2]
def QNLP.proc.HammingDistance.HammingDistanceExpITheta.calc (self, reg_mem, reg_aux, pattern)
Definition at line 85 of file HammingDistance.py.
     def calc(self, reg_mem, reg_aux, pattern):
         self.encode_hamming(reg_mem, reg_aux, pattern)
References QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming().
encode_hamming()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming (self, reg_mem, reg_aux, pattern)
Definition at line 69 of file HammingDistance.py.
     def encode_hamming(self, reg_mem, reg_aux, pattern):
         self.sim.applyGateH(reg_aux[-2])
         self._step1(reg_mem, reg_aux, pattern)
         self._step2(reg_mem, reg_aux)
         self._step3(reg_mem, reg_aux)
         self._step4(reg_mem, reg_aux)
         self.sim.applyGateH(reg_aux[-2])
         self._step5(reg_aux)
References QNLP.proc.HammingDistance.HammingDistanceExpITheta._step1(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step2(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step3(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step4(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step5(), and QNLP.proc.HammingDistance.HammingDistance.sim.
Referenced by QNLP.proc.HammingDistance.HammingDistanceExpITheta.calc().
hamming_aux_overwrite()
def QNLP.proc.HammingDistance.HammingDistanceExpITheta.hamming_aux_overwrite (self, reg_mem, reg_aux)
Definition at line 78 of file HammingDistance.py.
     def hamming_aux_overwrite(self, reg_mem, reg_aux):
         for i in range(len(reg_mem)):
             self.sim.applyGateX(reg_aux[i])
             self.sim.applyGateCCX(reg_mem[i], reg_aux[i], reg_aux[-1])
             self.sim.applyGateX(reg_aux[i])
             self.sim.applyGateCSwap(reg_mem[i], reg_aux[i], reg_aux[-1])
References QNLP.proc.HammingDistance.HammingDistance.sim.
Field Documentation
num_bits
QNLP.proc.HammingDistance.HammingDistance.num_bits inherited
Definition at line 18 of file HammingDistance.py.
Referenced by QNLP.proc.HammingDistance.HammingDistanceGroupRotate._oracle_angle_map().
sim
QNLP.proc.HammingDistance.HammingDistance.sim inherited
Definition at line 19 of file HammingDistance.py.
Referenced by QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._encodePattern(), QNLP.proc.HammingDistance.HammingDistanceOverwriteAux._overwriteAux(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step1(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step2(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step3(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step4(), QNLP.proc.HammingDistance.HammingDistanceExpITheta._step5(), QNLP.proc.HammingDistance.HammingDistanceGroupRotate.calc(), QNLP.proc.HammingDistance.HammingDistanceExpITheta.encode_hamming(), and QNLP.proc.HammingDistance.HammingDistanceExpITheta.hamming_aux_overwrite().
The documentation for this class was generated from the following file:
/Users/mlxd/Desktop/intel-qnlp-rc2/modules/py/pkgs/QNLP/proc/HammingDistance.py