QNLP: QNLP::DBHelper Class Reference
QNLP::DBHelper Class Reference
#include <db_helper.hpp>
Public Member Functions
DBHelper ()
DBHelper (const std::string filename)
~DBHelper ()
int openDB (const std::string filename)
Opens the requested database, and gives the return code of the operation. If the DB pointer has already been associated with data, then the return code is 0, and no operation is performed.
void closeDB ()
Closes the database if the DB pointer is open.
sqlite3 * getDBRef ()
Returns a pointer to the DB object.
std::string getFilename ()
Get the name of the opened database.
Private Attributes
sqlite3 * db_ptr
std::string db_filename
Detailed Description
Definition at line 35 of file db_helper.hpp.
Constructor & Destructor Documentation
DBHelper() [1/2]
DBHelper::DBHelper ()
Definition at line 13 of file db_helper.cpp.
 : db_ptr(nullptr){};
DBHelper() [2/2]
DBHelper::DBHelper (const std::string filename)
Definition at line 15 of file db_helper.cpp.
                                            : db_ptr(nullptr), db_filename(filename){
     SQL_RETURN_CHECK ( DBHelper::openDB(filename), SQLITE_OK );
 }
References openDB(), and SQL_RETURN_CHECK.
~DBHelper()
DBHelper::~DBHelper ()
Definition at line 19 of file db_helper.cpp.
                    {
     DBHelper::closeDB();
 }
References closeDB().
Member Function Documentation
closeDB()
void DBHelper::closeDB ()
Closes the database if the DB pointer is open.
Definition at line 23 of file db_helper.cpp.
                       {
     if(this->db_ptr != nullptr ){
     //    std::cout << "CLOSING " << db_filename << std::endl;
         SQL_RETURN_CHECK ( sqlite3_close(this->db_ptr), SQLITE_OK );
     }
     db_filename.clear();
     db_ptr = nullptr;
 }
References db_filename, db_ptr, and SQL_RETURN_CHECK.
Referenced by openDB(), and ~DBHelper().
getDBRef()
sqlite3 * DBHelper::getDBRef ()
Returns a pointer to the DB object.
Returns
sqlite3*
Definition at line 47 of file db_helper.cpp.
{
     return this->db_ptr;
 }
References db_ptr.
Referenced by TEST_CASE().
getFilename()
std::string DBHelper::getFilename ()
Get the name of the opened database.
Returns
std::string
Definition at line 51 of file db_helper.cpp.
{
     return this->db_filename;
 }
References db_filename.
Referenced by TEST_CASE().
openDB()
int DBHelper::openDB (const std::string filename)
Opens the requested database, and gives the return code of the operation. If the DB pointer has already been associated with data, then the return code is 0, and no operation is performed.
Parameters
string Path to database on filesystem.
Returns
int Return code of the DB access.
Definition at line 32 of file db_helper.cpp.
{
     if(this->db_ptr == nullptr){
         this->db_filename = filename;
     //    std::cout << "OPENING " << filename << std::endl;
         int rc = sqlite3_open_v2( (const char *) filename.c_str(), &this->db_ptr, SQLITE_OPEN_READWRITE, NULL);
         if (rc != SQLITE_OK){
             DBHelper::closeDB();
         }
         return rc;
     } else {
         return 0;
     }
 }
References closeDB(), db_filename, and db_ptr.
Referenced by DBHelper(), and QNLP::CorpusUtils::loadData().
Field Documentation
db_filename
std::string QNLP::DBHelper::db_filename private
Definition at line 72 of file db_helper.hpp.
Referenced by closeDB(), getFilename(), and openDB().
db_ptr
sqlite3* QNLP::DBHelper::db_ptr private
Definition at line 71 of file db_helper.hpp.
Referenced by closeDB(), getDBRef(), and openDB().
The documentation for this class was generated from the following files:
/Users/mlxd/Desktop/tmp/intel-qnlp-api/modules/io/db/db_helper.hpp
/Users/mlxd/Desktop/tmp/intel-qnlp-api/modules/io/db/db_helper.cpp