QNLP: QNLP::GateWriter Class Reference
QNLP::GateWriter Class Reference
#include <GateWriter.hpp>
Public Member Functions
GateWriter ()
Construct a new Gate Writer object.
GateWriter (std::string latexCSVFilename, std::string matrixFilename)
Construct a new Gate Writer object.
~GateWriter ()
Destroy the Gate Writer object.
void gateOut (std::string gateLabel, std::string matrixVals)
Writes the given matrix to matrix_val_out. Assumes matrix type is printable.
void segmentMarkerOut (std::string segmentString)
Marks the output file with a string pattern to allow easy of parsing for gates to algorithm operations.
void oneQubitGateCall (const std::string &gateLabel, const std::string &matrixVals, std::size_t gate_idx)
Writes the single qubit gate to disk. -1 used to denote lack of control line.
void twoQubitGateCall (const std::string gateLabel, const std::string matrixVals, std::size_t gate_ctrl_idx, std::size_t gate_tgt_idx)
Writes the controlled gate to disk.
std::unordered_set< std::string > & getAppliedGates ()
Return the map of all applied gates so far.
Private Attributes
std::ofstream latex_csv_out
std::ofstream matrix_val_out
std::unordered_set< std::string > gates
Detailed Description
Definition at line 9 of file GateWriter.hpp.
Constructor & Destructor Documentation
GateWriter() [1/2]
QNLP::GateWriter::GateWriter () inline
Construct a new Gate Writer object.
Definition at line 19 of file GateWriter.hpp.
                      : GateWriter("qnlp_gate_calls.csv", "qnlp_matrices.log"){
         }
GateWriter() [2/2]
QNLP::GateWriter::GateWriter (std::string latexCSVFilename, std::string matrixFilename) inline
Construct a new Gate Writer object.
Parameters
latexCSVFilename Filename for Latex CSV
matrixFilename Filename for matrix
Definition at line 28 of file GateWriter.hpp.
{
             //Check if file exists, add header upon creation if not
             std::ifstream file_exists(latexCSVFilename.c_str()) ;
             latex_csv_out.open ( latexCSVFilename, std::ofstream::out | std::ofstream::app );
             matrix_val_out.open( matrixFilename, std::ofstream::out | std::ofstream::app );
             if (!(bool) file_exists)
                 latex_csv_out << "gate_label,gate_ctrl,gate_tgt,gate_value" << std::endl;
         }
References latex_csv_out, and matrix_val_out.
~GateWriter()
QNLP::GateWriter::~GateWriter () inline
Destroy the Gate Writer object.
Definition at line 43 of file GateWriter.hpp.
                      {
             latex_csv_out  << "\n" << std::endl;
             matrix_val_out << "\n" << std::endl;
             latex_csv_out.close();
             matrix_val_out.close();
         }
References latex_csv_out, and matrix_val_out.
Member Function Documentation
gateOut()
void QNLP::GateWriter::gateOut (std::string gateLabel, std::string matrixVals) inline
Writes the given matrix to matrix_val_out. Assumes matrix type is printable.
Parameters
matrix
Definition at line 56 of file GateWriter.hpp.
{
             if( !gates.count(gateLabel)){
                 matrix_val_out << gateLabel << "," << matrixVals << std::endl;
                 gates.insert(gateLabel);
             }
         }
References gates, and matrix_val_out.
Referenced by twoQubitGateCall().
getAppliedGates()
std::unordered_set<std::string>& QNLP::GateWriter::getAppliedGates () inline
Return the map of all applied gates so far.
Returns
std::unordered_map<std::string, Mat2x2Type>&
Definition at line 101 of file GateWriter.hpp.
{
             return gates;
         }
References gates.
oneQubitGateCall()
void QNLP::GateWriter::oneQubitGateCall (const std::string & gateLabel, const std::string & matrixVals, std::size_t gate_idx) inline
Writes the single qubit gate to disk. -1 used to denote lack of control line.
Parameters
gateLabel std::string used to label gate name.
matrixVal The matrix representing the gate.
gate_idx The qubit index to apply gate.
Definition at line 79 of file GateWriter.hpp.
{
             twoQubitGateCall(gateLabel, matrixVals, -1, gate_idx);
         }
References twoQubitGateCall().
Referenced by TEST_CASE().
segmentMarkerOut()
void QNLP::GateWriter::segmentMarkerOut (std::string segmentString) inline
Marks the output file with a string pattern to allow easy of parsing for gates to algorithm operations.
Parameters
segmentString The name of the segment to print into the file.
Definition at line 68 of file GateWriter.hpp.
{
             latex_csv_out << "#!#{" << segmentString << "}#!#" << std::endl;
         }
References latex_csv_out.
twoQubitGateCall()
void QNLP::GateWriter::twoQubitGateCall (const std::string gateLabel, const std::string matrixVals, std::size_t gate_ctrl_idx, std::size_t gate_tgt_idx) inline
Writes the controlled gate to disk.
Parameters
gateLabel std::string used to label gate name.
matrixVal The matrix representing the gate.
gate_ctrl_idx The qubit index for the gate control line
gate_tgt_idx The qubit index for the gate target line
Definition at line 91 of file GateWriter.hpp.
{
             latex_csv_out << gateLabel << "," << gate_ctrl_idx << "," << gate_tgt_idx << "," << matrixVals << std::endl;
             gateOut(gateLabel, matrixVals);
         }
References gateOut(), and latex_csv_out.
Referenced by oneQubitGateCall().
Field Documentation
gates
std::unordered_set<std::string> QNLP::GateWriter::gates private
Definition at line 12 of file GateWriter.hpp.
Referenced by gateOut(), and getAppliedGates().
latex_csv_out
std::ofstream QNLP::GateWriter::latex_csv_out private
Definition at line 11 of file GateWriter.hpp.
Referenced by GateWriter(), segmentMarkerOut(), twoQubitGateCall(), and ~GateWriter().
matrix_val_out
std::ofstream QNLP::GateWriter::matrix_val_out private
Definition at line 11 of file GateWriter.hpp.
Referenced by gateOut(), GateWriter(), and ~GateWriter().
The documentation for this class was generated from the following file:
/Users/mlxd/Desktop/tmp/intel-qnlp-api/modules/io/GateWriter/GateWriter.hpp