QNLP: QNLP::GateCache< SimulatorType > Class Template Reference
QNLP::GateCache< SimulatorType > Class Template Reference
Class to cache intermediate matrix values used within other parts of the computation. Heavily depended upon by NCU to store sqrt matrix values following Barenco et al. (1995) decomposition.
#include <GateCache.hpp>
Public Types
using GateType = decltype(std::declval< SimulatorType >().getGateX())
Public Member Functions
GateCache ()
GateCache (SimulatorType &qSim)
GateCache (SimulatorType &qSim, std::size_t default_depth)
~GateCache ()
void clearCache ()
void initCache (SimulatorType &sim, std::size_t sqrt_depth)
Initialise the gate cache with PauliX,Y,Z and H up to a given sqrt depth.
void addToCache (SimulatorType &sim, const std::string gateLabel, const GateType &gate, std::size_t max_depth)
Adds new gate to the cache up to a given sqrt depth.
Data Fields
std::unordered_map< std::string, std::vector< std::pair< GateType, GateType > > > gateCacheMap
Private Attributes
std::size_t cache_depth
Detailed Description
template<class SimulatorType>
class QNLP::GateCache< SimulatorType >
Class to cache intermediate matrix values used within other parts of the computation. Heavily depended upon by NCU to store sqrt matrix values following Barenco et al. (1995) decomposition.
Template Parameters
SimulatorType The simulator type with SimulatorGeneral as base class
Definition at line 95 of file GateCache.hpp.
Member Typedef Documentation
GateType
template<class SimulatorType> using QNLP::GateCache< SimulatorType >::GateType = decltype(std::declval<SimulatorType>().getGateX())
Definition at line 114 of file GateCache.hpp.
Constructor & Destructor Documentation
GateCache() [1/3]
template<class SimulatorType> QNLP::GateCache< SimulatorType >::GateCache () inline
Definition at line 100 of file GateCache.hpp.
 : cache_depth(0) { };
GateCache() [2/3]
template<class SimulatorType> QNLP::GateCache< SimulatorType >::GateCache (SimulatorType & qSim) inline
Definition at line 102 of file GateCache.hpp.
                                        : GateCache() {
             //initCache(qSim, 16);
             //cache_depth = 16;
         }
GateCache() [3/3]
template<class SimulatorType> QNLP::GateCache< SimulatorType >::GateCache (SimulatorType & qSim, std::size_t default_depth) inline
Definition at line 107 of file GateCache.hpp.
                                                                 : cache_depth(default_depth) {
             initCache(qSim, cache_depth);
         }
References QNLP::GateCache< SimulatorType >::cache_depth, and QNLP::GateCache< SimulatorType >::initCache().
~GateCache()
template<class SimulatorType> QNLP::GateCache< SimulatorType >::~GateCache () inline
Definition at line 111 of file GateCache.hpp.
 { clearCache(); }
References QNLP::GateCache< SimulatorType >::clearCache().
Member Function Documentation
addToCache()
template<class SimulatorType> void QNLP::GateCache< SimulatorType >::addToCache (SimulatorType & sim, const std::string gateLabel, const GateType & gate, std::size_t max_depth) inline
Adds new gate to the cache up to a given sqrt depth.
Parameters
gateLabel Label of gate to index into map
gate Gate matrix
max_depth Depth of calculations for sqrt and associate adjoints
Definition at line 165 of file GateCache.hpp.
{
             if(max_depth <= cache_depth && gateCacheMap.find(gateLabel) != gateCacheMap.end() ){
                 return;
             }
             else if(max_depth > cache_depth){
                 initCache(sim, max_depth);
             }
             std::vector< std::pair<GateType, GateType> > v;
             v.reserve(max_depth + 1);
             v.push_back(std::make_pair( gate, adjointMatrix( gate ) ) );
             for( std::size_t depth = 1; depth <= max_depth; depth++ ){
                 auto m = matrixSqrt<GateType>( v[depth-1].first );
                 v.emplace(v.begin() + depth, std::make_pair( m, adjointMatrix( m ) ) );
             }
             gateCacheMap.emplace(std::make_pair(gateLabel, v) );
         }
References QNLP::adjointMatrix(), QNLP::GateCache< SimulatorType >::cache_depth, QNLP::GateCache< SimulatorType >::gateCacheMap, QNLP::GateCache< SimulatorType >::initCache(), CircuitPrinter.circuit_printer::max_depth, and ncu_opt_tester::sim.
clearCache()
template<class SimulatorType> void QNLP::GateCache< SimulatorType >::clearCache () inline
Definition at line 119 of file GateCache.hpp.
{
             gateCacheMap.clear();
             cache_depth = 0;
         }
References QNLP::GateCache< SimulatorType >::cache_depth, and QNLP::GateCache< SimulatorType >::gateCacheMap.
Referenced by QNLP::GateCache< SimulatorType >::~GateCache().
initCache()
template<class SimulatorType> void QNLP::GateCache< SimulatorType >::initCache (SimulatorType & sim, std::size_t sqrt_depth) inline
Initialise the gate cache with PauliX,Y,Z and H up to a given sqrt depth.
Parameters
sim The simulator object
sqrt_depth The depth to which calculate sqrt matrices and their respective adjoints
Definition at line 130 of file GateCache.hpp.
{
             // If we do not have a sufficient circuit depth, clear and rebuild up to given depth.
             // Could ideally use existing values and rebuild from lowest depth, but consider this
             // after we have a working implementation.
             if(cache_depth < sqrt_depth ){
                 gateCacheMap.clear();
                 cache_depth = 0;
             }
             if (gateCacheMap.empty()){
                 gateCacheMap["X"] = std::vector< std::pair<GateType, GateType> > { std::make_pair( sim.getGateX(), adjointMatrix( sim.getGateX() ) ) };
                 gateCacheMap["Y"] = std::vector< std::pair<GateType, GateType> > { std::make_pair( sim.getGateY(), adjointMatrix( sim.getGateY() ) ) };
                 gateCacheMap["Z"] = std::vector< std::pair<GateType, GateType> > { std::make_pair( sim.getGateZ(), adjointMatrix( sim.getGateZ() ) ) };
                 gateCacheMap["H"] = std::vector< std::pair<GateType, GateType> > { std::make_pair( sim.getGateH(), adjointMatrix( sim.getGateH() ) ) };
                 for( std::size_t depth = 1; depth <= sqrt_depth; depth++ ){
                     for( auto& kv : gateCacheMap ){
                         kv.second.reserve(sqrt_depth + 1);
                         auto m = matrixSqrt<GateType>(kv.second[depth-1].first);
                         kv.second.emplace(kv.second.begin() + depth, std::make_pair( m, adjointMatrix( m ) ) );
                     }
                 }
                 cache_depth = sqrt_depth;
             }
         }
References QNLP::adjointMatrix(), QNLP::GateCache< SimulatorType >::cache_depth, QNLP::GateCache< SimulatorType >::gateCacheMap, and ncu_opt_tester::sim.
Referenced by QNLP::GateCache< SimulatorType >::addToCache(), and QNLP::GateCache< SimulatorType >::GateCache().
Field Documentation
cache_depth
template<class SimulatorType> std::size_t QNLP::GateCache< SimulatorType >::cache_depth private
Definition at line 97 of file GateCache.hpp.
Referenced by QNLP::GateCache< SimulatorType >::addToCache(), QNLP::GateCache< SimulatorType >::clearCache(), QNLP::GateCache< SimulatorType >::GateCache(), and QNLP::GateCache< SimulatorType >::initCache().
gateCacheMap
template<class SimulatorType> std::unordered_map<std::string, std::vector< std::pair<GateType, GateType> > > QNLP::GateCache< SimulatorType >::gateCacheMap
Definition at line 117 of file GateCache.hpp.
Referenced by QNLP::GateCache< SimulatorType >::addToCache(), QNLP::GateCache< SimulatorType >::clearCache(), and QNLP::GateCache< SimulatorType >::initCache().
The documentation for this class was generated from the following file:
/Users/mlxd/Desktop/intel-qnlp-rc2/modules/utils/GateCache.hpp